# Generated by Django 2.2.1 on 2019-09-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='operate_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_time', models.DateTimeField()),
                ('done_time', models.DateTimeField()),
                ('time_gap', models.DurationField()),
                ('click_command', models.CharField(max_length=20)),
            ],
        ),
    ]
